# Generated by Django 6.0.5 on 2026-05-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('url', 'Ссылка'), ('text', 'Текст'), ('media', 'Медиа')], max_length=20)),
                ('target', models.TextField()),
                ('verdict', models.CharField(max_length=120)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_title', models.CharField(max_length=160)),
                ('scenario_text', models.TextField()),
                ('correct_answer', models.BooleanField()),
                ('user_answer', models.BooleanField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
