# Generated by Django 6.0.5 on 2026-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybershield_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_type',
            field=models.CharField(choices=[('url', 'URL Checker'), ('text', 'Text Analyzer'), ('media', 'Image Scanner')], max_length=20),
        ),
    ]
